name: Build EXEs from Unity Scripts

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build scraping-title.exe
      run: pyinstaller --onefile --distpath unity/dist unity/scraping-title.py

    - name: Build scraping-image.exe
      run: pyinstaller --onefile --distpath unity/dist unity/scraping-image.py

    - name: Debug all .exe files
      run: Get-ChildItem -Recurse -Filter *.exe

    - name: Upload both .exe files
      uses: actions/upload-artifact@v4
      with:
        name: unity-exe-files
        path: |
          unity/dist/scraping-title.exe
          unity/dist/scraping-image.exe
